<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="16" passed="7" failed="9" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-17T10:15:19 ICT" name="Suite" finished-at="2024-06-17T10:19:22 ICT" duration-ms="242675">
    <groups>
    </groups>
    <test started-at="2024-06-17T10:15:19 ICT" name="Railway - Login" finished-at="2024-06-17T10:16:01 ICT" duration-ms="41991">
      <class name="Login">
        <test-method is-config="true" signature="setup()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:19 ICT" name="setup" finished-at="2024-06-17T10:15:25 ICT" duration-ms="6113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC001()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:25 ICT" name="TC001" description="User can log into Railway with valid username and password" finished-at="2024-06-17T10:15:28 ICT" duration-ms="2684" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome ihqmosdc@sharklasers.com] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome ihqmosdc@sharklasers.com] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at pages.LoginPage.verifyWelcomeMes(LoginPage.java:39)
at Login.TC001(Login.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:28 ICT" name="clean" finished-at="2024-06-17T10:15:28 ICT" duration-ms="216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:28 ICT" name="setup" finished-at="2024-06-17T10:15:34 ICT" duration-ms="5758" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC002()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:34 ICT" name="TC002" description="User cannot login with blank &quot;Username&quot; textbox" finished-at="2024-06-17T10:15:36 ICT" duration-ms="1857" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:36 ICT" name="clean" finished-at="2024-06-17T10:15:36 ICT" duration-ms="212" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:36 ICT" name="setup" finished-at="2024-06-17T10:15:42 ICT" duration-ms="5854" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC003()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:42 ICT" name="TC003" description="User cannot log into Railway with invalid password" finished-at="2024-06-17T10:15:44 ICT" duration-ms="1897" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at pages.LoginPage.verifyErrorMes(LoginPage.java:27)
at Login.TC003(Login.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC003 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:44 ICT" name="clean" finished-at="2024-06-17T10:15:44 ICT" duration-ms="331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:44 ICT" name="setup" finished-at="2024-06-17T10:15:51 ICT" duration-ms="6951" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC004()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:51 ICT" name="TC004" description="System shows message when user enters wrong password many times" finished-at="2024-06-17T10:15:53 ICT" duration-ms="1902" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element don't display.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element don't display.
at org.testng.Assert.fail(Assert.java:111)
at utils.SeleniumHelper.verifyEleDisplay(SeleniumHelper.java:51)
at Login.TC004(Login.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC004 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:53 ICT" name="clean" finished-at="2024-06-17T10:15:53 ICT" duration-ms="238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:53 ICT" name="setup" finished-at="2024-06-17T10:15:59 ICT" duration-ms="5794" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC005()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:15:59 ICT" name="TC005" description="User can&#039;t login with an account hasn&#039;t been activated" finished-at="2024-06-17T10:16:01 ICT" duration-ms="1959" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC005 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:Login@27ae2fd0]" started-at="2024-06-17T10:16:01 ICT" name="clean" finished-at="2024-06-17T10:16:01 ICT" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
      </class> <!-- Login -->
    </test> <!-- Railway - Login -->
    <test started-at="2024-06-17T10:16:01 ICT" name="Railway - Logout" finished-at="2024-06-17T10:16:12 ICT" duration-ms="10818">
      <class name="Logout">
        <test-method is-config="true" signature="setup()[pri:0, instance:Logout@29626d54]" started-at="2024-06-17T10:16:01 ICT" name="setup" finished-at="2024-06-17T10:16:08 ICT" duration-ms="6458" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC6()[pri:0, instance:Logout@29626d54]" started-at="2024-06-17T10:16:08 ICT" name="TC6" description="User is redirected to Home page after logging out" finished-at="2024-06-17T10:16:12 ICT" duration-ms="4168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC6 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:Logout@29626d54]" started-at="2024-06-17T10:16:12 ICT" name="clean" finished-at="2024-06-17T10:16:12 ICT" duration-ms="191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
      </class> <!-- Logout -->
    </test> <!-- Railway - Logout -->
    <test started-at="2024-06-17T10:16:12 ICT" name="Railway - Register" finished-at="2024-06-17T10:17:10 ICT" duration-ms="57390">
      <class name="CreateAccount">
        <test-method is-config="true" signature="setup()[pri:0, instance:CreateAccount@4b0b0854]" started-at="2024-06-17T10:16:12 ICT" name="setup" finished-at="2024-06-17T10:16:18 ICT" duration-ms="5689" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC007()[pri:0, instance:CreateAccount@4b0b0854]" started-at="2024-06-17T10:16:18 ICT" name="TC007" description="User can&#039;t create account with an already in-use email" finished-at="2024-06-17T10:16:20 ICT" duration-ms="1946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC007 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:CreateAccount@4b0b0854]" started-at="2024-06-17T10:16:20 ICT" name="clean" finished-at="2024-06-17T10:16:20 ICT" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:CreateAccount@4b0b0854]" started-at="2024-06-17T10:16:20 ICT" name="setup" finished-at="2024-06-17T10:16:25 ICT" duration-ms="5424" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC008()[pri:0, instance:CreateAccount@4b0b0854]" started-at="2024-06-17T10:16:25 ICT" name="TC008" description="User can&#039;t create account while password and PID fields are empty" finished-at="2024-06-17T10:16:33 ICT" duration-ms="7287" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Invalid password length] but found [Invalid password length.],
expected [Invalid ID length] but found [Invalid ID length.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Invalid password length] but found [Invalid password length.],
expected [Invalid ID length] but found [Invalid ID length.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at CreateAccount.TC008(CreateAccount.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC008 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:CreateAccount@4b0b0854]" started-at="2024-06-17T10:16:33 ICT" name="clean" finished-at="2024-06-17T10:16:33 ICT" duration-ms="235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:CreateAccount@4b0b0854]" started-at="2024-06-17T10:16:33 ICT" name="setup" finished-at="2024-06-17T10:16:38 ICT" duration-ms="5562" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC009()[pri:0, instance:CreateAccount@4b0b0854]" started-at="2024-06-17T10:16:38 ICT" name="TC009" description="User create and activate account" finished-at="2024-06-17T10:17:09 ICT" duration-ms="30782" status="FAIL">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for element to be clickable: By.xpath: //tbody[@id='email_list']//tr[td[text()='thanhletraining03@gmail.com ']] (tried for 20 second(s) with 500 milliseconds interval)
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.61, chrome: {chromedriverVersion: 126.0.6478.61 (8dc092df54ce..., userDataDir: C:\Users\ADMIN\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:56462}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:56462/devtoo..., se:cdpVersion: 126.0.6478.61, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 4fb35e2228b728c241eefabfc8e44de1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.xpath: //tbody[@id='email_list']//tr[td[text()='thanhletraining03@gmail.com ']] (tried for 20 second(s) with 500 milliseconds interval)
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.61, chrome: {chromedriverVersion: 126.0.6478.61 (8dc092df54ce..., userDataDir: C:\Users\ADMIN\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:56462}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:56462/devtoo..., se:cdpVersion: 126.0.6478.61, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 4fb35e2228b728c241eefabfc8e44de1
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at pages.MailPage.confirmAccount(MailPage.java:33)
at CreateAccount.TC009(CreateAccount.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC009 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:CreateAccount@4b0b0854]" started-at="2024-06-17T10:17:09 ICT" name="clean" finished-at="2024-06-17T10:17:10 ICT" duration-ms="287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
      </class> <!-- CreateAccount -->
    </test> <!-- Railway - Register -->
    <test started-at="2024-06-17T10:17:10 ICT" name="Railway - Reset password" finished-at="2024-06-17T10:18:22 ICT" duration-ms="72382">
      <class name="ResetPwd">
        <test-method is-config="true" signature="setup()[pri:0, instance:ResetPwd@67a20f67]" started-at="2024-06-17T10:17:10 ICT" name="setup" finished-at="2024-06-17T10:17:16 ICT" duration-ms="6030" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC010()[pri:0, instance:ResetPwd@67a20f67]" started-at="2024-06-17T10:17:16 ICT" name="TC010" description="Reset password shows error if the new password is same as current" finished-at="2024-06-17T10:17:46 ICT" duration-ms="30122" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The new password cannot be the same with the current password] but found [Password changed! Click here to login.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The new password cannot be the same with the current password] but found [Password changed! Click here to login.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ResetPwd.TC010(ResetPwd.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC010 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:ResetPwd@67a20f67]" started-at="2024-06-17T10:17:46 ICT" name="clean" finished-at="2024-06-17T10:17:46 ICT" duration-ms="239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:ResetPwd@67a20f67]" started-at="2024-06-17T10:17:46 ICT" name="setup" finished-at="2024-06-17T10:17:52 ICT" duration-ms="5740" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC011()[pri:0, instance:ResetPwd@67a20f67]" started-at="2024-06-17T10:17:52 ICT" name="TC011" description="Reset password shows error if the new password and confirm password doesn&#039;t match" finished-at="2024-06-17T10:18:22 ICT" duration-ms="29986" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC011 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:ResetPwd@67a20f67]" started-at="2024-06-17T10:18:22 ICT" name="clean" finished-at="2024-06-17T10:18:22 ICT" duration-ms="263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
      </class> <!-- ResetPwd -->
    </test> <!-- Railway - Reset password -->
    <test started-at="2024-06-17T10:18:22 ICT" name="Railway - Book ticket" finished-at="2024-06-17T10:19:07 ICT" duration-ms="45198">
      <class name="BookTicket">
        <test-method is-config="true" signature="setup()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:18:22 ICT" name="setup" finished-at="2024-06-17T10:18:28 ICT" duration-ms="6098" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC012()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:18:28 ICT" name="TC012" description="User can book 1 ticket at a time" finished-at="2024-06-17T10:18:33 ICT" duration-ms="5103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC012 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:18:33 ICT" name="clean" finished-at="2024-06-17T10:18:33 ICT" duration-ms="217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:18:33 ICT" name="setup" finished-at="2024-06-17T10:18:39 ICT" duration-ms="6056" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC013()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:18:39 ICT" name="TC013" description="User can book many tickets at a time" finished-at="2024-06-17T10:18:45 ICT" duration-ms="5353" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//table//td[count(//th[text()='Depart Date']/preceding-sibling::th) + 1]"}
  (Session info: chrome=126.0.6478.61)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [67b9cd066bd5c19f0086c908ff5b3c8c, findElement {using=xpath, value=//table//td[count(//th[text()='Depart Date']/preceding-sibling::th) + 1]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.61, chrome: {chromedriverVersion: 126.0.6478.61 (8dc092df54ce..., userDataDir: C:\Users\ADMIN\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:56720}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:56720/devtoo..., se:cdpVersion: 126.0.6478.61, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 67b9cd066bd5c19f0086c908ff5b3c8c]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//table//td[count(//th[text()='Depart Date']/preceding-sibling::th) + 1]"}
  (Session info: chrome=126.0.6478.61)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [67b9cd066bd5c19f0086c908ff5b3c8c, findElement {using=xpath, value=//table//td[count(//th[text()='Depart Date']/preceding-sibling::th) + 1]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.61, chrome: {chromedriverVersion: 126.0.6478.61 (8dc092df54ce..., userDataDir: C:\Users\ADMIN\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:56720}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:56720/devtoo..., se:cdpVersion: 126.0.6478.61, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 67b9cd066bd5c19f0086c908ff5b3c8c
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:349)
at utils.SeleniumHelper.getText(SeleniumHelper.java:33)
at pages.BookTicketsPage.getInfoBookTicketSucc(BookTicketsPage.java:30)
at BookTicket.TC013(BookTicket.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC013 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:18:45 ICT" name="clean" finished-at="2024-06-17T10:18:45 ICT" duration-ms="190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:18:45 ICT" name="setup" finished-at="2024-06-17T10:18:50 ICT" duration-ms="5444" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC014()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:18:50 ICT" name="TC014" description="User can check price of ticket from Timetable" finished-at="2024-06-17T10:18:55 ICT" duration-ms="4521" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC014 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:18:55 ICT" name="clean" finished-at="2024-06-17T10:18:55 ICT" duration-ms="184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method is-config="true" signature="setup()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:18:55 ICT" name="setup" finished-at="2024-06-17T10:19:01 ICT" duration-ms="6269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC015()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:19:01 ICT" name="TC015" description="User can book ticket from Timetable" finished-at="2024-06-17T10:19:07 ICT" duration-ms="5583" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Ticket booked successfully!] but found [Book ticket]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Ticket booked successfully!] but found [Book ticket]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at BookTicket.TC015(BookTicket.java:148)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC015 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:BookTicket@6a400542]" started-at="2024-06-17T10:19:07 ICT" name="clean" finished-at="2024-06-17T10:19:07 ICT" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
      </class> <!-- BookTicket -->
    </test> <!-- Railway - Book ticket -->
    <test started-at="2024-06-17T10:19:07 ICT" name="Railway - Cancel booking" finished-at="2024-06-17T10:19:22 ICT" duration-ms="14854">
      <class name="CancelBooking">
        <test-method is-config="true" signature="setup()[pri:0, instance:CancelBooking@4ac3c60d]" started-at="2024-06-17T10:19:07 ICT" name="setup" finished-at="2024-06-17T10:19:15 ICT" duration-ms="7765" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC016()[pri:0, instance:CancelBooking@4ac3c60d]" started-at="2024-06-17T10:19:15 ICT" name="TC016" description="User can cancel a ticket" finished-at="2024-06-17T10:19:22 ICT" duration-ms="6914" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element exists]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element exists
at org.testng.Assert.fail(Assert.java:111)
at utils.SeleniumHelper.verifyEleNoDiplay(SeleniumHelper.java:58)
at pages.MyTicketPage.verifyTicketNoDisplay(MyTicketPage.java:23)
at CancelBooking.TC016(CancelBooking.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC016 -->
        <test-method is-config="true" signature="clean()[pri:0, instance:CancelBooking@4ac3c60d]" started-at="2024-06-17T10:19:22 ICT" name="clean" finished-at="2024-06-17T10:19:22 ICT" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
      </class> <!-- CancelBooking -->
    </test> <!-- Railway - Cancel booking -->
  </suite> <!-- Suite -->
</testng-results>
